version: 3

tasks:
  default:
    silent: true
    cmds:
      - task -l

  down:
    desc: Stop the docker containers
    cmds:
      - docker compose down

  up:
    desc: Stand up the docker containers
    cmds:
      - docker compose up -d minio init-minio

  test:unit:
    desc: Run the unit tests
    cmds:
      - go test ./...

  build:
    desc: Build the docker image
    cmds:
      - docker build . -f Dockerfile

  serve:
    desc: Run the api
    cmds:
      - go run main.go serve

  jwt:secret:
    desc: Generate a JWT sercet
    silent: true
    cmds:
      - go run main.go secrets jwt

  encryption:key:
    desc: Generate a JWT sercet
    silent: true
    cmds:
      - go run main.go secrets key
